ARG ARCHIMATE_CI_IMAGE=ghcr.io/woozymasta/archimate-ci-image
ARG ARCHIMATE_CI_VERSION=5.2.0

FROM $ARCHIMATE_CI_IMAGE:$ARCHIMATE_CI_VERSION AS base

ARG UID=1000

RUN set -eux; \
    mv /root/.archi /archi/; \
    groupadd --gid "$UID" archi; \
    useradd --uid "$UID" --gid archi --shell /bin/bash \
      --home-dir /archi --create-home archi; \
    chown -R "$UID:0" /archi; \
    chmod -R g+rw /archi

USER $UID
